// GENERATED by scripts/gen-bridges.ts (scripts/lib/gen-host-swift.ts) from the host tables of
// sdk/src/bridges/*.d.ts — do not edit. The Apple host's side of the contract: the C tables of
// creator-pkg/host.gen.h filled with @convention(c) trampolines over the Swift HostServices
// (HostContract.swift, the same model). A C slot carries no context, so the trampolines reach the
// tables through the process-wide statics below; an optional Swift slot left nil leaves the C slot
// NULL (the runtime hides the JS method). String / byte results are malloc'd copies the runtime frees.
import Foundation
import CLeCodesCore

enum HostGlue {
    // The Swift tables the trampolines call (set by bind; nil = the host has none).
    static var t_gl: LeCodesCore.HostGL?
    static var t_scene2d: LeCodesCore.HostScene2d?
    static var t_ui: LeCodesCore.HostUI?
    static var t_canvas: LeCodesCore.HostCanvas?
    static var t_app: LeCodesCore.HostApp?
    static var t_device: LeCodesCore.HostDevice?
    static var t_fetch: LeCodesCore.HostFetch?
    static var t_files: LeCodesCore.HostFiles?
    static var t_storage: LeCodesCore.HostStorage?
    static var t_socket: LeCodesCore.HostSocket?
    static var t_service: LeCodesCore.HostService?
    static var t_input: LeCodesCore.HostInput?
    static var t_media: LeCodesCore.HostMedia?

    // The C tables the runtime keeps pointers to for the life of the process (never freed).
    static let c_gl = UnsafeMutablePointer<CLeCodesCore.HostGL>.allocate(capacity: 1)
    static let c_scene2d = UnsafeMutablePointer<CLeCodesCore.HostScene2d>.allocate(capacity: 1)
    static let c_ui = UnsafeMutablePointer<CLeCodesCore.HostUI>.allocate(capacity: 1)
    static let c_canvas = UnsafeMutablePointer<CLeCodesCore.HostCanvas>.allocate(capacity: 1)
    static let c_app = UnsafeMutablePointer<CLeCodesCore.HostApp>.allocate(capacity: 1)
    static let c_device = UnsafeMutablePointer<CLeCodesCore.HostDevice>.allocate(capacity: 1)
    static let c_fetch = UnsafeMutablePointer<CLeCodesCore.HostFetch>.allocate(capacity: 1)
    static let c_files = UnsafeMutablePointer<CLeCodesCore.HostFiles>.allocate(capacity: 1)
    static let c_storage = UnsafeMutablePointer<CLeCodesCore.HostStorage>.allocate(capacity: 1)
    static let c_socket = UnsafeMutablePointer<CLeCodesCore.HostSocket>.allocate(capacity: 1)
    static let c_service = UnsafeMutablePointer<CLeCodesCore.HostService>.allocate(capacity: 1)
    static let c_input = UnsafeMutablePointer<CLeCodesCore.HostInput>.allocate(capacity: 1)
    static let c_media = UnsafeMutablePointer<CLeCodesCore.HostMedia>.allocate(capacity: 1)
    static let c_services = UnsafeMutablePointer<CLeCodesCore.HostServices>.allocate(capacity: 1)

    // ---- conversions -------------------------------------------------------------------------
    static func string(_ p: UnsafePointer<CChar>?) -> String { p.map { String(cString: $0) } ?? "" }
    static func strings(_ p: UnsafePointer<UnsafePointer<CChar>?>?, _ count: Int32) -> [String] {
        guard let p = p, count > 0 else { return [] }
        return (0..<Int(count)).map { string(p[$0]) }
    }
    static func array<C, S>(_ p: UnsafePointer<C>?, _ count: Int32, _ make: (C) -> S) -> [S] {
        guard let p = p, count > 0 else { return [] }
        return (0..<Int(count)).map { make(p[$0]) }
    }
    /// A malloc'd UTF-8 copy for a `char*` result (the runtime frees it); nil stays nil.
    static func cString(_ s: String?) -> UnsafeMutablePointer<CChar>? { s.flatMap { strdup($0) } }
    /// A malloc'd copy of bytes plus a trailing NUL for a `void*` / `uint8_t*` result; nil → nil / 0.
    static func bytes(_ b: [UInt8]?, _ outSize: UnsafeMutablePointer<Int>?) -> UnsafeMutableRawPointer? {
        guard let b = b else { outSize?.pointee = 0; return nil }
        let p = malloc(b.count + 1)!
        b.withUnsafeBytes { src in if b.count > 0 { p.copyMemory(from: src.baseAddress!, byteCount: b.count) } }
        p.storeBytes(of: 0, toByteOffset: b.count, as: UInt8.self)
        outSize?.pointee = b.count
        return p
    }
    /// An `@out N` result: the N floats copied into the slot's buffer, false for nil.
    static func floats(_ v: [Float]?, _ out: UnsafeMutablePointer<Float>?, _ n: Int) -> Bool {
        guard let v = v, let out = out, v.count >= n else { return false }
        for i in 0..<n { out[i] = v[i] }
        return true
    }

    /// `export type FetchFormEntry` (fetch.d.ts): the C struct → the Swift one.
    static func makeFetchFormEntry(_ c: CLeCodesCore.FetchFormEntry) -> LeCodesCore.FetchFormEntry {
        LeCodesCore.FetchFormEntry(key: string(c.key), value: c.value.map { String(cString: $0) }, bufferId: c.bufferId, filename: c.filename.map { String(cString: $0) })
    }

    // ---- HostGL (gl.d.ts) — an optional table
    static func fill_gl(_ t: LeCodesCore.HostGL) {
        t_gl = t
        let c = c_gl
        c.initialize(to: CLeCodesCore.HostGL())
        if t.getGLContext != nil { c.pointee.getGLContext = { return HostGlue.t_gl!.getGLContext!() } }
        if t.engineCreated != nil { c.pointee.engineCreated = { HostGlue.t_gl!.engineCreated!() } }
        if t.createGLView != nil { c.pointee.createGLView = { HostGlue.t_gl!.createGLView!() } }
        if t.closeScene != nil { c.pointee.closeScene = { HostGlue.t_gl!.closeScene!() } }
        c.pointee.createTexture = { a0, a1, a2, a3 in HostGlue.t_gl!.createTexture(systemId: a0, flags: a1, onComplete: a2, onReject: a3) }
        if t.createMediaPlayerTexture != nil { c.pointee.createMediaPlayerTexture = { a0 in return HostGlue.t_gl!.createMediaPlayerTexture!(a0) } }
        if t.launchAR != nil { c.pointee.launchAR = { a0, a1, a2 in HostGlue.t_gl!.launchAR!(a0, a1, a2) } }
        if t.stopAR != nil { c.pointee.stopAR = { HostGlue.t_gl!.stopAR!() } }
        if t.launchVR != nil { c.pointee.launchVR = { a0, a1, a2 in HostGlue.t_gl!.launchVR!(a0, a1, a2) } }
        if t.stopVR != nil { c.pointee.stopVR = { HostGlue.t_gl!.stopVR!() } }
        if t.createARController != nil { c.pointee.createARController = { a0, a1, a2 in HostGlue.t_gl!.createARController!(a0, a1, HostGlue.string(a2)) } }
        if t.createRootAnchor != nil { c.pointee.createRootAnchor = { a0, a1 in HostGlue.t_gl!.createRootAnchor!(a0, a1) } }
        if t.createAnchor != nil { c.pointee.createAnchor = { a0, a1, a2, a3 in HostGlue.t_gl!.createAnchor!(a0, a1, a2, a3) } }
    }

    // ---- HostScene2d (2d.d.ts) — an optional table
    static func fill_scene2d(_ t: LeCodesCore.HostScene2d) {
        t_scene2d = t
        let c = c_scene2d
        c.initialize(to: CLeCodesCore.HostScene2d())
        if t.open2DScene != nil { c.pointee.open2DScene = { a0 in HostGlue.t_scene2d!.open2DScene!(a0) } }
        if t.close2DScene != nil { c.pointee.close2DScene = { HostGlue.t_scene2d!.close2DScene!() } }
        if t.init2D != nil { c.pointee.init2D = { HostGlue.t_scene2d!.init2D!() } }
    }

    // ---- HostUI (tree.d.ts)
    static func fill_ui(_ t: LeCodesCore.HostUI) {
        t_ui = t
        let c = c_ui
        c.initialize(to: CLeCodesCore.HostUI())
        c.pointee.nodeFactory = { a0, a1, a2, a3 in HostGlue.t_ui!.nodeFactory(id: Int(bitPattern: a0), type: HostGlue.string(a1), parent: Int(bitPattern: a2), index: a3) }
        c.pointee.setPropertyString = { a0, a1, a2 in HostGlue.t_ui!.setPropertyString(id: Int(bitPattern: a0), prop: HostGlue.string(a1), value: a2.map { String(cString: $0) }) }
        c.pointee.setPropertyInt = { a0, a1, a2 in HostGlue.t_ui!.setPropertyInt(id: Int(bitPattern: a0), prop: HostGlue.string(a1), value: a2) }
        c.pointee.setFlags = { a0, a1 in HostGlue.t_ui!.setFlags(id: Int(bitPattern: a0), mask: a1) }
        c.pointee.insertNode = { a0, a1, a2 in HostGlue.t_ui!.insertNode(parent: Int(bitPattern: a0), child: Int(bitPattern: a1), index: a2) }
        c.pointee.removeNode = { a0, a1 in HostGlue.t_ui!.removeNode(parent: Int(bitPattern: a0), child: Int(bitPattern: a1)) }
        c.pointee.releaseNode = { a0 in HostGlue.t_ui!.releaseNode(id: Int(bitPattern: a0)) }
        c.pointee.openView = { a0, a1, a2, a3, a4, a5 in HostGlue.t_ui!.openView(kind: a0, node: Int(bitPattern: a1), id: a2, viewName: HostGlue.string(a3), paramsJson: HostGlue.string(a4), above: a5) }
        c.pointee.dropView = { a0, a1, a2 in HostGlue.t_ui!.dropView(kind: a0, node: Int(bitPattern: a1), id: a2) }
        c.pointee.closeView = { HostGlue.t_ui!.closeView() }
        if t.isViewSupported != nil { c.pointee.isViewSupported = { a0 in return HostGlue.t_ui!.isViewSupported!(HostGlue.string(a0)) } }
        if t.viewVersion != nil { c.pointee.viewVersion = { a0 in return HostGlue.t_ui!.viewVersion!(HostGlue.string(a0)) } }
        if t.viewCall != nil { c.pointee.viewCall = { a0, a1, a2, a3, a4 in HostGlue.t_ui!.viewCall!(a0, HostGlue.string(a1), WireIn(a2), a3, a4) } }
        c.pointee.widgetOpen = { a0, a1, a2, a3 in HostGlue.t_ui!.widgetOpen(node: Int(bitPattern: a0), ownerKind: a1, ownerId: a2, ownerNode: Int(bitPattern: a3)) }
        c.pointee.widgetClose = { a0 in HostGlue.t_ui!.widgetClose(node: Int(bitPattern: a0)) }
        c.pointee.registerFont = { a0, a1, a2, a3, a4, a5 in HostGlue.t_ui!.registerFont(url: HostGlue.string(a0), fontFamily: HostGlue.string(a1), weight: a2, style: a3, onComplete: a4, onReject: a5) }
        c.pointee.showToast = { a0, a1 in HostGlue.t_ui!.showToast(message: HostGlue.string(a0), duration: a1) }
        c.pointee.getButtonPressed = { a0 in return HostGlue.t_ui!.getButtonPressed(node: Int(bitPattern: a0)) }
        c.pointee.getTextValue = { a0 in return HostGlue.cString(HostGlue.t_ui!.getTextValue(node: Int(bitPattern: a0))) ?? strdup("") }
        if t.getBoundingRect != nil { c.pointee.getBoundingRect = { a0, a1 in return HostGlue.floats(HostGlue.t_ui!.getBoundingRect!(Int(bitPattern: a0)), a1, 4) } }
        if t.touchHandler != nil { c.pointee.touchHandler = { a0, a1, a2, a3 in HostGlue.t_ui!.touchHandler!(a0, a1, a2, Int(bitPattern: a3)) } }
        if t.longPressHandler != nil { c.pointee.longPressHandler = { a0, a1 in HostGlue.t_ui!.longPressHandler!(a0, Int(bitPattern: a1)) } }
        c.pointee.vlistScroll = { a0, a1, a2 in HostGlue.t_ui!.vlistScroll(node: Int(bitPattern: a0), scrollY: a1, animated: a2) }
        if t.pagerCommand != nil { c.pointee.pagerCommand = { a0, a1, a2 in HostGlue.t_ui!.pagerCommand!(Int(bitPattern: a0), HostGlue.string(a1), a2) } }
        if t.pagerShowPage != nil { c.pointee.pagerShowPage = { a0, a1, a2 in HostGlue.t_ui!.pagerShowPage!(Int(bitPattern: a0), Int(bitPattern: a1), a2) } }
        if t.pagerDropPage != nil { c.pointee.pagerDropPage = { a0, a1 in HostGlue.t_ui!.pagerDropPage!(Int(bitPattern: a0), Int(bitPattern: a1)) } }
        if t.pagerPageMounted != nil { c.pointee.pagerPageMounted = { a0, a1 in HostGlue.t_ui!.pagerPageMounted!(Int(bitPattern: a0), a1) } }
        if t.tweenClaim != nil { c.pointee.tweenClaim = { a0, a1, a2, a3, a4, a5, a6, a7, a8, a9 in return HostGlue.t_ui!.tweenClaim!(Int(bitPattern: a0), HostGlue.string(a1), a2, UnsafeBufferPointer(start: a3, count: Int(a4)), a5, a6, a7, a8, a9) } }
        if t.tweenRelease != nil { c.pointee.tweenRelease = { a0, a1, a2 in HostGlue.t_ui!.tweenRelease!(Int(bitPattern: a0), HostGlue.string(a1), a2) } }
    }

    // ---- HostCanvas (canvas.d.ts) — an optional table
    static func fill_canvas(_ t: LeCodesCore.HostCanvas) {
        t_canvas = t
        let c = c_canvas
        c.initialize(to: CLeCodesCore.HostCanvas())
        c.pointee.paint = { a0, a1, a2, a3, a4, a5, a6, a7 in HostGlue.t_canvas!.paint(surfaceId: a0, pw: a1, ph: a2, scale: a3, words: UnsafeBufferPointer(start: a4, count: Int(a5)), strings: HostGlue.strings(a6, a7)) }
        c.pointee.measureText = { a0, a1, a2, a3, a4, a5 in HostGlue.t_canvas!.measureText(text: HostGlue.string(a0), family: HostGlue.string(a1), size: a2, weight: a3, italic: a4, out: a5!) }
        c.pointee.decodeImage = { a0, a1, a2 in return HostGlue.t_canvas!.decodeImage(bufferId: a0, surfaceId: a1, size: a2!) }
        c.pointee.readPixels = { a0, a1 in return HostGlue.bytes(HostGlue.t_canvas!.readPixels(surfaceId: a0, size: a1!), nil).map { $0.assumingMemoryBound(to: UInt8.self) } }
        c.pointee.releaseSurface = { a0 in HostGlue.t_canvas!.releaseSurface(surfaceId: a0) }
    }

    // ---- HostApp (app.d.ts)
    static func fill_app(_ t: LeCodesCore.HostApp) {
        t_app = t
        let c = c_app
        c.initialize(to: CLeCodesCore.HostApp())
        if t.state != nil { c.pointee.state = { return HostGlue.cString(HostGlue.t_app!.state!()) ?? strdup("") } }
        if t.isOnline != nil { c.pointee.isOnline = { return HostGlue.t_app!.isOnline!() } }
        if t.openUrl != nil { c.pointee.openUrl = { a0 in HostGlue.t_app!.openUrl!(HostGlue.string(a0)) } }
        if t.setOrientation != nil { c.pointee.setOrientation = { a0 in HostGlue.t_app!.setOrientation!(HostGlue.string(a0)) } }
        if t.worldChange != nil { c.pointee.worldChange = { a0, a1 in HostGlue.t_app!.worldChange!(a0.map { String(cString: $0) }, a1) } }
        if t.exit != nil { c.pointee.exit = { HostGlue.t_app!.exit!() } }
    }

    // ---- HostDevice (device.d.ts)
    static func fill_device(_ t: LeCodesCore.HostDevice) {
        t_device = t
        let c = c_device
        c.initialize(to: CLeCodesCore.HostDevice())
        c.pointee.platform = UnsafePointer(strdup(t.platform))   // kept for the process (Core may replace it)
        c.pointee.language = UnsafePointer(strdup(t.language))   // kept for the process (Core may replace it)
        c.pointee.pixelRatio = t.pixelRatio
        if t.setPreciseTouch != nil { c.pointee.setPreciseTouch = { a0 in HostGlue.t_device!.setPreciseTouch!(a0) } }
        if t.vibrate != nil { c.pointee.vibrate = { a0 in HostGlue.t_device!.vibrate!(HostGlue.string(a0)) } }
        if t.setStatsOverlay != nil { c.pointee.setStatsOverlay = { a0 in HostGlue.t_device!.setStatsOverlay!(a0) } }
        if t.statsOverlay != nil { c.pointee.statsOverlay = { return HostGlue.t_device!.statsOverlay!() } }
        if t.motionAvailable != nil { c.pointee.motionAvailable = { return HostGlue.t_device!.motionAvailable!() } }
        if t.motionStart != nil { c.pointee.motionStart = { a0 in return HostGlue.t_device!.motionStart!(a0) } }
        if t.motionStop != nil { c.pointee.motionStop = { HostGlue.t_device!.motionStop!() } }
        if t.motionSample != nil { c.pointee.motionSample = { a0 in return HostGlue.floats(HostGlue.t_device!.motionSample!(), a0, 8) } }
        if t.clipboardWrite != nil { c.pointee.clipboardWrite = { a0 in HostGlue.t_device!.clipboardWrite!(HostGlue.string(a0)) } }
        if t.clipboardRead != nil { c.pointee.clipboardRead = { a0, a1 in HostGlue.t_device!.clipboardRead!(a0, a1) } }
        if t.share != nil { c.pointee.share = { a0, a1 in HostGlue.t_device!.share!(a0, a1.map { String(cString: $0) }) } }
        if t.openFilePicker != nil { c.pointee.openFilePicker = { a0, a1, a2, a3 in HostGlue.t_device!.openFilePicker!(a0, a1, a2, a3.map { String(cString: $0) }) } }
        if t.requestCamera != nil { c.pointee.requestCamera = { a0, a1 in HostGlue.t_device!.requestCamera!(a0, a1) } }
    }

    // ---- HostFetch (fetch.d.ts)
    static func fill_fetch(_ t: LeCodesCore.HostFetch) {
        t_fetch = t
        let c = c_fetch
        c.initialize(to: CLeCodesCore.HostFetch())
        c.pointee.local = { a0 in return HostGlue.t_fetch!.local(path: HostGlue.string(a0)) }
        if t.dispose != nil { c.pointee.dispose = { a0 in HostGlue.t_fetch!.dispose!(a0) } }
        c.pointee.request = { a0, a1, a2, a3, a4, a5, a6, a7, a8, a9 in HostGlue.t_fetch!.request(url: HostGlue.string(a0), method: HostGlue.string(a1), headers: HostGlue.strings(a2, a3), body: a4.map { String(cString: $0) }, form: HostGlue.array(a5, a6, HostGlue.makeFetchFormEntry), onComplete: a7, onReject: a8, onProgress: a9) }
        c.pointee.buffer = { a0, a1, a2 in return HostGlue.bytes(HostGlue.t_fetch!.buffer(id: a0, addByte: a1), a2) }
        c.pointee.bufferSlice = { a0, a1, a2, a3, a4 in return HostGlue.bytes(HostGlue.t_fetch!.bufferSlice(id: a0, start: a1, end: a2, addByte: a3), a4) }
        c.pointee.systemBuffer = { a0, a1 in return HostGlue.bytes(HostGlue.t_fetch!.systemBuffer(id: a0), a1) }
        if t.putBuffer != nil { c.pointee.putBuffer = { a0, a1 in return HostGlue.t_fetch!.putBuffer!(UnsafeBufferPointer(start: a0, count: Int(a1))) } }
    }

    // ---- HostFiles (files.d.ts) — an optional table
    static func fill_files(_ t: LeCodesCore.HostFiles) {
        t_files = t
        let c = c_files
        c.initialize(to: CLeCodesCore.HostFiles())
        c.pointee.readBytes = { a0, a1, a2 in HostGlue.t_files!.readBytes(path: HostGlue.string(a0), onComplete: a1, onReject: a2) }
        c.pointee.readText = { a0, a1, a2 in HostGlue.t_files!.readText(path: HostGlue.string(a0), onComplete: a1, onReject: a2) }
        c.pointee.remove = { a0, a1, a2, a3 in HostGlue.t_files!.remove(path: HostGlue.string(a0), recursive: a1, onComplete: a2, onReject: a3) }
        c.pointee.mkdir = { a0, a1, a2 in HostGlue.t_files!.mkdir(path: HostGlue.string(a0), onComplete: a1, onReject: a2) }
        c.pointee.list = { a0, a1, a2, a3 in HostGlue.t_files!.list(path: HostGlue.string(a0), recursive: a1, onComplete: a2, onReject: a3) }
        c.pointee.stat = { a0, a1, a2 in HostGlue.t_files!.stat(path: HostGlue.string(a0), onComplete: a1, onReject: a2) }
        c.pointee.write = { a0, a1, a2, a3, a4, a5 in HostGlue.t_files!.write(path: HostGlue.string(a0), data: UnsafeBufferPointer(start: a1, count: Int(a2)), append: a3, onComplete: a4, onReject: a5) }
    }

    // ---- HostStorage (storage.d.ts)
    static func fill_storage(_ t: LeCodesCore.HostStorage) {
        t_storage = t
        let c = c_storage
        c.initialize(to: CLeCodesCore.HostStorage())
        if t.load != nil { c.pointee.load = { a0 in return HostGlue.cString(HostGlue.t_storage!.load!(HostGlue.string(a0))) } }
        if t.save != nil { c.pointee.save = { a0, a1 in HostGlue.t_storage!.save!(HostGlue.string(a0), HostGlue.string(a1)) } }
    }

    // ---- HostSocket (socket.d.ts)
    static func fill_socket(_ t: LeCodesCore.HostSocket) {
        t_socket = t
        let c = c_socket
        c.initialize(to: CLeCodesCore.HostSocket())
        c.pointee.send = { a0, a1 in HostGlue.t_socket!.send(id: a0, message: HostGlue.string(a1)) }
        c.pointee.open = { a0, a1 in return HostGlue.t_socket!.open(url: HostGlue.string(a0), onMessage: a1) }
        c.pointee.close = { a0 in HostGlue.t_socket!.close(id: a0) }
    }

    // ---- HostService (service.d.ts) — an optional table
    static func fill_service(_ t: LeCodesCore.HostService) {
        t_service = t
        let c = c_service
        c.initialize(to: CLeCodesCore.HostService())
        c.pointee.supported = { a0 in return HostGlue.t_service!.supported(name: HostGlue.string(a0)) }
        c.pointee.open = { a0, a1, a2 in return HostGlue.t_service!.open(name: HostGlue.string(a0), params: HostGlue.string(a1), onEvent: a2) }
        c.pointee.close = { a0 in HostGlue.t_service!.close(serviceId: a0) }
        if t.version != nil { c.pointee.version = { a0 in return HostGlue.t_service!.version!(HostGlue.string(a0)) } }
        c.pointee.call = { a0, a1, a2, a3, a4 in HostGlue.t_service!.call(serviceId: a0, method: HostGlue.string(a1), args: WireIn(a2), onComplete: a3, onError: a4) }
    }

    // ---- HostInput (input.d.ts)
    static func fill_input(_ t: LeCodesCore.HostInput) {
        t_input = t
        let c = c_input
        c.initialize(to: CLeCodesCore.HostInput())
        if t.key != nil { c.pointee.key = { a0, a1 in return HostGlue.t_input!.key!(HostGlue.string(a0), a1) } }
        if t.read != nil { c.pointee.read = { a0 in return HostGlue.t_input!.read!(a0) } }
        if t.setPointerLock != nil { c.pointee.setPointerLock = { a0 in return HostGlue.t_input!.setPointerLock!(a0) } }
        if t.rumble != nil { c.pointee.rumble = { a0, a1, a2, a3 in return HostGlue.t_input!.rumble!(a0, a1, a2, a3) } }
        if t.keyboardHeight != nil { c.pointee.keyboardHeight = { return HostGlue.t_input!.keyboardHeight!() } }
    }

    // ---- HostMedia (media.d.ts) — an optional table
    static func fill_media(_ t: LeCodesCore.HostMedia) {
        t_media = t
        let c = c_media
        c.initialize(to: CLeCodesCore.HostMedia())
        c.pointee.setVolume = { a0, a1 in HostGlue.t_media!.setVolume(id: a0, volume: a1) }
        if t.time != nil { c.pointee.time = { a0 in return HostGlue.t_media!.time!(a0) } }
        if t.setTime != nil { c.pointee.setTime = { a0, a1 in HostGlue.t_media!.setTime!(a0, a1) } }
        if t.duration != nil { c.pointee.duration = { a0 in return HostGlue.t_media!.duration!(a0) } }
        c.pointee.createAudio = { a0, a1 in return HostGlue.t_media!.createAudio(src: HostGlue.string(a0), onFinished: a1) }
        c.pointee.createVideo = { a0, a1 in return HostGlue.t_media!.createVideo(src: HostGlue.string(a0), onFinished: a1) }
        c.pointee.setLoop = { a0, a1 in HostGlue.t_media!.setLoop(id: a0, loop: a1) }
        c.pointee.setPlaying = { a0, a1 in HostGlue.t_media!.setPlaying(id: a0, playing: a1) }
        if t.remove != nil { c.pointee.remove = { a0 in HostGlue.t_media!.remove!(a0) } }
    }

    /// Fill every C table from the Swift HostServices and hand them to the runtime (setHostServices):
    /// ONCE, before initJS. A nil optional table leaves its pointer NULL.
    static func bind(_ s: LeCodesCore.HostServices) {
        c_services.initialize(to: CLeCodesCore.HostServices())
        if let t = s.gl { fill_gl(t); c_services.pointee.gl = UnsafePointer(c_gl) }
        if let t = s.scene2d { fill_scene2d(t); c_services.pointee.scene2d = UnsafePointer(c_scene2d) }
        fill_ui(s.ui)
        c_services.pointee.ui = UnsafePointer(c_ui)
        if let t = s.canvas { fill_canvas(t); c_services.pointee.canvas = UnsafePointer(c_canvas) }
        fill_app(s.app)
        c_services.pointee.app = UnsafePointer(c_app)
        fill_device(s.device)
        c_services.pointee.device = UnsafePointer(c_device)
        fill_fetch(s.fetch)
        c_services.pointee.fetch = UnsafePointer(c_fetch)
        if let t = s.files { fill_files(t); c_services.pointee.files = UnsafePointer(c_files) }
        fill_storage(s.storage)
        c_services.pointee.storage = UnsafePointer(c_storage)
        fill_socket(s.socket)
        c_services.pointee.socket = UnsafePointer(c_socket)
        if let t = s.service { fill_service(t); c_services.pointee.service = UnsafePointer(c_service) }
        fill_input(s.input)
        c_services.pointee.input = UnsafePointer(c_input)
        if let t = s.media { fill_media(t); c_services.pointee.media = UnsafePointer(c_media) }
        lc_setHostServices(c_services)
    }
}
