// GENERATED by scripts/gen-bridges.ts from the host tables of sdk/src/bridges/*.d.ts — do not edit.
// The host contract as Swift: one protocol per table of creator-pkg/host.gen.h. A required slot is a
// method; an optional one is a nullable closure property with a default of nil (the slot is absent —
// the runtime skips the feature and the SDK's feature-detect stays false). Callbacks arrive as heap
// handles (JSCallback) the host settles through dispatchHeapCall / jsFree. `ptr` slots carry the
// host's own node objects (Unmanaged references); the C glue copies byte and string results.
import Foundation

public typealias JSCallback = Int

/// `export type FetchFormEntry` of sdk/src/bridges/fetch.d.ts.
public struct FetchFormEntry {
    public var key: String
    public var value: String?
    public var bufferId: Int32
    public var filename: String?
}

/// The host's gl table (export interface HostGL of sdk/src/bridges/gl.d.ts) — optional as a whole (the host may provide none).
public protocol HostGL: AnyObject {
    /// Optional slot: nil = absent.
    var getGLContext: (() -> UnsafeMutableRawPointer?)? { get }
    /// Optional slot: nil = absent.
    var engineCreated: (() -> Void)? { get }
    /// Optional slot: nil = absent.
    var createGLView: (() -> Void)? { get }
    /// Optional slot: nil = absent.
    var closeScene: (() -> Void)? { get }
    func createTexture(systemId: Int32, flags: UInt32, onComplete: JSCallback, onReject: JSCallback)
    /// Optional slot: nil = absent.
    var createMediaPlayerTexture: ((Int32) -> Int32)? { get }
    /// Optional slot: nil = absent.
    var launchAR: ((UInt32, JSCallback, JSCallback) -> Void)? { get }
    /// Optional slot: nil = absent.
    var stopAR: (() -> Void)? { get }
    /// Optional slot: nil = absent.
    var launchVR: ((UInt32, JSCallback, JSCallback) -> Void)? { get }
    /// Optional slot: nil = absent.
    var stopVR: (() -> Void)? { get }
    /// Optional slot: nil = absent.
    var createARController: ((UInt32, UInt32, String) -> Void)? { get }
    /// Optional slot: nil = absent.
    var createRootAnchor: ((UInt32, UInt32) -> Void)? { get }
    /// Optional slot: nil = absent.
    var createAnchor: ((UInt32, UInt32, Float, Int32) -> Void)? { get }
}
public extension HostGL {
    var getGLContext: (() -> UnsafeMutableRawPointer?)? { nil }
    var engineCreated: (() -> Void)? { nil }
    var createGLView: (() -> Void)? { nil }
    var closeScene: (() -> Void)? { nil }
    var createMediaPlayerTexture: ((Int32) -> Int32)? { nil }
    var launchAR: ((UInt32, JSCallback, JSCallback) -> Void)? { nil }
    var stopAR: (() -> Void)? { nil }
    var launchVR: ((UInt32, JSCallback, JSCallback) -> Void)? { nil }
    var stopVR: (() -> Void)? { nil }
    var createARController: ((UInt32, UInt32, String) -> Void)? { nil }
    var createRootAnchor: ((UInt32, UInt32) -> Void)? { nil }
    var createAnchor: ((UInt32, UInt32, Float, Int32) -> Void)? { nil }
}

/// The host's scene2d table (export interface HostScene2d of sdk/src/bridges/2d.d.ts) — optional as a whole (the host may provide none).
public protocol HostScene2d: AnyObject {
    /// Optional slot: nil = absent.
    var open2DScene: ((Int32) -> Void)? { get }
    /// Optional slot: nil = absent.
    var close2DScene: (() -> Void)? { get }
    /// Optional slot: nil = absent.
    var init2D: (() -> Void)? { get }
}
public extension HostScene2d {
    var open2DScene: ((Int32) -> Void)? { nil }
    var close2DScene: (() -> Void)? { nil }
    var init2D: (() -> Void)? { nil }
}

/// The host's ui table (export interface HostUI of sdk/src/bridges/tree.d.ts).
public protocol HostUI: AnyObject {
    func nodeFactory(id: Int, type: String, parent: Int, index: Int32)
    func setPropertyString(id: Int, prop: String, value: String?)
    func setPropertyInt(id: Int, prop: String, value: Int32)
    func setFlags(id: Int, mask: UInt32)
    func insertNode(parent: Int, child: Int, index: UInt16)
    func removeNode(parent: Int, child: Int)
    func releaseNode(id: Int)
    func openView(kind: UInt8, node: Int, id: Int32, viewName: String, paramsJson: String, above: Bool)
    func dropView(kind: UInt8, node: Int, id: Int32)
    func closeView()
    /// Optional slot: nil = absent.
    var isViewSupported: ((String) -> Bool)? { get }
    /// Optional slot: nil = absent.
    var viewVersion: ((String) -> Int32)? { get }
    /// Optional slot: nil = absent.
    var viewCall: ((Int32, String, WireIn, JSCallback, JSCallback) -> Void)? { get }
    func widgetOpen(node: Int, ownerKind: UInt8, ownerId: Int32, ownerNode: Int)
    func widgetClose(node: Int)
    func registerFont(url: String, fontFamily: String, weight: Int32, style: Int32, onComplete: JSCallback, onReject: JSCallback)
    func showToast(message: String, duration: Int32)
    func getButtonPressed(node: Int) -> Bool
    func getTextValue(node: Int) -> String
    /// Optional slot: nil = absent.
    var getBoundingRect: ((Int) -> [Float]?)? { get }
    /// Optional slot: nil = absent.
    var touchHandler: ((Int32, Bool, UInt8, Int) -> Void)? { get }
    /// Optional slot: nil = absent.
    var longPressHandler: ((Int32, Int) -> Void)? { get }
    func vlistScroll(node: Int, scrollY: Float, animated: Bool)
    /// Optional slot: nil = absent.
    var pagerCommand: ((Int, String, Bool) -> Void)? { get }
    /// Optional slot: nil = absent.
    var pagerShowPage: ((Int, Int, Bool) -> Void)? { get }
    /// Optional slot: nil = absent.
    var pagerDropPage: ((Int, Int) -> Void)? { get }
    /// Optional slot: nil = absent.
    var pagerPageMounted: ((Int, Bool) -> Void)? { get }
    /// Optional slot: nil = absent.
    var tweenClaim: ((Int, String, Int32, UnsafeBufferPointer<Float>, Float, Float, Int32, Bool, Float) -> Bool)? { get }
    /// Optional slot: nil = absent.
    var tweenRelease: ((Int, String, UInt8) -> Void)? { get }
}
public extension HostUI {
    var isViewSupported: ((String) -> Bool)? { nil }
    var viewVersion: ((String) -> Int32)? { nil }
    var viewCall: ((Int32, String, WireIn, JSCallback, JSCallback) -> Void)? { nil }
    var getBoundingRect: ((Int) -> [Float]?)? { nil }
    var touchHandler: ((Int32, Bool, UInt8, Int) -> Void)? { nil }
    var longPressHandler: ((Int32, Int) -> Void)? { nil }
    var pagerCommand: ((Int, String, Bool) -> Void)? { nil }
    var pagerShowPage: ((Int, Int, Bool) -> Void)? { nil }
    var pagerDropPage: ((Int, Int) -> Void)? { nil }
    var pagerPageMounted: ((Int, Bool) -> Void)? { nil }
    var tweenClaim: ((Int, String, Int32, UnsafeBufferPointer<Float>, Float, Float, Int32, Bool, Float) -> Bool)? { nil }
    var tweenRelease: ((Int, String, UInt8) -> Void)? { nil }
}

/// The host's canvas table (export interface HostCanvas of sdk/src/bridges/canvas.d.ts) — optional as a whole (the host may provide none).
public protocol HostCanvas: AnyObject {
    func paint(surfaceId: Int32, pw: Int32, ph: Int32, scale: Float, words: UnsafeBufferPointer<Float>, strings: [String])
    func measureText(text: String, family: String, size: Float, weight: Int32, italic: Bool, out: UnsafeMutablePointer<Float>)
    func decodeImage(bufferId: Int32, surfaceId: Int32, size: UnsafeMutablePointer<Int32>) -> Bool
    func readPixels(surfaceId: Int32, size: UnsafeMutablePointer<Int32>) -> [UInt8]?
    func releaseSurface(surfaceId: Int32)
}

/// The host's side of _creatorApp (sdk/src/bridges/app.d.ts).
public protocol HostApp: AnyObject {
    /// Optional slot: nil = absent.
    var state: (() -> String)? { get }
    /// Optional slot: nil = absent.
    var isOnline: (() -> Bool)? { get }
    /// Optional slot: nil = absent.
    var openUrl: ((String) -> Void)? { get }
    /// Optional slot: nil = absent.
    var setOrientation: ((String) -> Void)? { get }
    /// Optional slot: nil = absent.
    var worldChange: ((String?, Bool) -> Void)? { get }
    /// Optional slot: nil = absent.
    var exit: (() -> Void)? { get }
}
public extension HostApp {
    var state: (() -> String)? { nil }
    var isOnline: (() -> Bool)? { nil }
    var openUrl: ((String) -> Void)? { nil }
    var setOrientation: ((String) -> Void)? { nil }
    var worldChange: ((String?, Bool) -> Void)? { nil }
    var exit: (() -> Void)? { nil }
}

/// The host's side of _creatorDevice (sdk/src/bridges/device.d.ts).
public protocol HostDevice: AnyObject {
    var platform: String { get }
    var language: String { get }
    var pixelRatio: Double { get }
    /// Optional slot: nil = absent.
    var setPreciseTouch: ((Bool) -> Void)? { get }
    /// Optional slot: nil = absent.
    var vibrate: ((String) -> Void)? { get }
    /// Optional slot: nil = absent.
    var setStatsOverlay: ((Bool) -> Void)? { get }
    /// Optional slot: nil = absent.
    var statsOverlay: (() -> Bool)? { get }
    /// Optional slot: nil = absent.
    var motionAvailable: (() -> Bool)? { get }
    /// Optional slot: nil = absent.
    var motionStart: ((Double) -> Bool)? { get }
    /// Optional slot: nil = absent.
    var motionStop: (() -> Void)? { get }
    /// Optional slot: nil = absent.
    var motionSample: (() -> [Float]?)? { get }
    /// Optional slot: nil = absent.
    var clipboardWrite: ((String) -> Void)? { get }
    /// Optional slot: nil = absent.
    var clipboardRead: ((JSCallback, JSCallback) -> Void)? { get }
    /// Optional slot: nil = absent.
    var share: ((Int32, String?) -> Void)? { get }
    /// Optional slot: nil = absent.
    var openFilePicker: ((JSCallback, JSCallback, Bool, String?) -> Void)? { get }
    /// Optional slot: nil = absent.
    var requestCamera: ((JSCallback, JSCallback) -> Void)? { get }
}
public extension HostDevice {
    var setPreciseTouch: ((Bool) -> Void)? { nil }
    var vibrate: ((String) -> Void)? { nil }
    var setStatsOverlay: ((Bool) -> Void)? { nil }
    var statsOverlay: (() -> Bool)? { nil }
    var motionAvailable: (() -> Bool)? { nil }
    var motionStart: ((Double) -> Bool)? { nil }
    var motionStop: (() -> Void)? { nil }
    var motionSample: (() -> [Float]?)? { nil }
    var clipboardWrite: ((String) -> Void)? { nil }
    var clipboardRead: ((JSCallback, JSCallback) -> Void)? { nil }
    var share: ((Int32, String?) -> Void)? { nil }
    var openFilePicker: ((JSCallback, JSCallback, Bool, String?) -> Void)? { nil }
    var requestCamera: ((JSCallback, JSCallback) -> Void)? { nil }
}

/// The host's side of _creatorFetch (sdk/src/bridges/fetch.d.ts).
public protocol HostFetch: AnyObject {
    func local(path: String) -> Int32
    /// Optional slot: nil = absent.
    var dispose: ((Int32) -> Void)? { get }
    func request(url: String, method: String, headers: [String], body: String?, form: [FetchFormEntry], onComplete: JSCallback, onReject: JSCallback, onProgress: JSCallback)
    func buffer(id: Int32, addByte: Bool) -> [UInt8]?
    func bufferSlice(id: Int32, start: Int32, end: Int32, addByte: Bool) -> [UInt8]?
    func systemBuffer(id: Int32) -> [UInt8]?
    /// Optional slot: nil = absent.
    var putBuffer: ((UnsafeBufferPointer<UInt8>) -> Int32)? { get }
}
public extension HostFetch {
    var dispose: ((Int32) -> Void)? { nil }
    var putBuffer: ((UnsafeBufferPointer<UInt8>) -> Int32)? { nil }
}

/// The host's side of _creatorFiles (sdk/src/bridges/files.d.ts) — optional as a whole (the host may provide none).
public protocol HostFiles: AnyObject {
    func readBytes(path: String, onComplete: JSCallback, onReject: JSCallback)
    func readText(path: String, onComplete: JSCallback, onReject: JSCallback)
    func remove(path: String, recursive: Bool, onComplete: JSCallback, onReject: JSCallback)
    func mkdir(path: String, onComplete: JSCallback, onReject: JSCallback)
    func list(path: String, recursive: Bool, onComplete: JSCallback, onReject: JSCallback)
    func stat(path: String, onComplete: JSCallback, onReject: JSCallback)
    func write(path: String, data: UnsafeBufferPointer<UInt8>, append: Bool, onComplete: JSCallback, onReject: JSCallback)
}

/// The host's side of _creatorStorage (sdk/src/bridges/storage.d.ts).
public protocol HostStorage: AnyObject {
    /// Optional slot: nil = absent.
    var load: ((String) -> String?)? { get }
    /// Optional slot: nil = absent.
    var save: ((String, String) -> Void)? { get }
}
public extension HostStorage {
    var load: ((String) -> String?)? { nil }
    var save: ((String, String) -> Void)? { nil }
}

/// The host's side of _creatorSocket (sdk/src/bridges/socket.d.ts).
public protocol HostSocket: AnyObject {
    func send(id: Int32, message: String)
    func open(url: String, onMessage: JSCallback) -> Int32
    func close(id: Int32)
}

/// The host's side of _creatorService (sdk/src/bridges/service.d.ts) — optional as a whole (the host may provide none).
public protocol HostService: AnyObject {
    func supported(name: String) -> Bool
    func open(name: String, params: String, onEvent: JSCallback) -> Int32
    func close(serviceId: Int32)
    /// Optional slot: nil = absent.
    var version: ((String) -> Int32)? { get }
    func call(serviceId: Int32, method: String, args: WireIn, onComplete: JSCallback, onError: JSCallback)
}
public extension HostService {
    var version: ((String) -> Int32)? { nil }
}

/// The host's side of _creatorInput (sdk/src/bridges/input.d.ts).
public protocol HostInput: AnyObject {
    /// Optional slot: nil = absent.
    var key: ((String, Int32) -> Bool)? { get }
    /// Optional slot: nil = absent.
    var read: ((Int32) -> Double)? { get }
    /// Optional slot: nil = absent.
    var setPointerLock: ((Bool) -> Bool)? { get }
    /// Optional slot: nil = absent.
    var rumble: ((Int32, Float, Float, Int32) -> Bool)? { get }
    /// Optional slot: nil = absent.
    var keyboardHeight: (() -> Double)? { get }
}
public extension HostInput {
    var key: ((String, Int32) -> Bool)? { nil }
    var read: ((Int32) -> Double)? { nil }
    var setPointerLock: ((Bool) -> Bool)? { nil }
    var rumble: ((Int32, Float, Float, Int32) -> Bool)? { nil }
    var keyboardHeight: (() -> Double)? { nil }
}

/// The host's side of _creatorMedia (sdk/src/bridges/media.d.ts) — optional as a whole (the host may provide none).
public protocol HostMedia: AnyObject {
    func setVolume(id: Int32, volume: Float)
    /// Optional slot: nil = absent.
    var time: ((Int32) -> Double)? { get }
    /// Optional slot: nil = absent.
    var setTime: ((Int32, Double) -> Void)? { get }
    /// Optional slot: nil = absent.
    var duration: ((Int32) -> Double)? { get }
    func createAudio(src: String, onFinished: JSCallback) -> Int32
    func createVideo(src: String, onFinished: JSCallback) -> Int32
    func setLoop(id: Int32, loop: Bool)
    func setPlaying(id: Int32, playing: Bool)
    /// Optional slot: nil = absent.
    var remove: ((Int32) -> Void)? { get }
}
public extension HostMedia {
    var time: ((Int32) -> Double)? { nil }
    var setTime: ((Int32, Double) -> Void)? { nil }
    var duration: ((Int32) -> Double)? { nil }
    var remove: ((Int32) -> Void)? { nil }
}

/// Every table of the contract, handed to the runtime once before initJS (nil = the host has none).
public struct HostServices {
    public var gl: HostGL?
    public var scene2d: HostScene2d?
    public var ui: HostUI
    public var canvas: HostCanvas?
    public var app: HostApp
    public var device: HostDevice
    public var fetch: HostFetch
    public var files: HostFiles?
    public var storage: HostStorage
    public var socket: HostSocket
    public var service: HostService?
    public var input: HostInput
    public var media: HostMedia?
    public init(gl: HostGL? = nil, scene2d: HostScene2d? = nil, ui: HostUI, canvas: HostCanvas? = nil, app: HostApp, device: HostDevice, fetch: HostFetch, files: HostFiles? = nil, storage: HostStorage, socket: HostSocket, service: HostService? = nil, input: HostInput, media: HostMedia? = nil) {
        self.gl = gl
        self.scene2d = scene2d
        self.ui = ui
        self.canvas = canvas
        self.app = app
        self.device = device
        self.fetch = fetch
        self.files = files
        self.storage = storage
        self.socket = socket
        self.service = service
        self.input = input
        self.media = media
    }
}
