// swift-tools-version:5.9
//
// LeCodesSDK 1.0.4 — binary distribution (no source).
// Generated by release.sh — do not edit by hand.
//
// Two variants, both vending the LeCodesSDK module (import is identical):
//   - LeCodesSDK-full: CreatorGL + filament (3D/AR)
//   - LeCodesSDK-core: UI only, ~15 MB smaller
//
// Full-variant consumers must also add LeCodesSDKResources.bundle (a release
// asset) to their app target's "Copy Bundle Resources".

import PackageDescription

let package = Package(
    name: "LeCodesSDK",
    platforms: [.iOS(.v14)],
    products: [
        .library(name: "LeCodesSDK-full", targets: ["LeCodesSDKFull"]),
        .library(name: "LeCodesSDK-core", targets: ["LeCodesSDKCore"]),
    ],
    targets: [
        .binaryTarget(
            name: "LeCodesSDKFull",
            url: "https://github.com/letary/lecodes-ios-sdk/releases/download/1.0.4/LeCodesSDK-full.xcframework.zip",
            checksum: "623b8673ba1f4f91edc6e3891670a5462d620bc7c7d91be9445dcdd93aa146db"
        ),
        .binaryTarget(
            name: "LeCodesSDKCore",
            url: "https://github.com/letary/lecodes-ios-sdk/releases/download/1.0.4/LeCodesSDK-core.xcframework.zip",
            checksum: "f1eebedb1c70b54e0f4fba2fd7abeef6797d90f6d2fafd897907a6f7d528d1ce"
        ),
    ]
)
