// swift-tools-version:5.9
//
// LeCodesSDK 1.6.0 — binary distribution (no source).
// Generated by release.sh — do not edit by hand.
//
// Four variants, all vending the LeCodesSDK module (import is identical):
//   - LeCodesSDK-full: everything (CreatorGL/filament+Jolt 3D/AR + Creator2D)
//   - LeCodesSDK-3d:   UI + CreatorGL/filament+Jolt (3D/AR), no 2D engine
//   - LeCodesSDK-2d:   UI + Creator2D, no 3D/AR
//   - LeCodesSDK-core: UI only
//
// full/3d consumers must also add LeCodesSDKResources.bundle (a release
// asset) to their app target's "Copy Bundle Resources".

import PackageDescription

let package = Package(
    name: "LeCodesSDK",
    platforms: [.iOS(.v14)],
    products: [
        .library(name: "LeCodesSDK-full", targets: ["LeCodesSDKFull"]),
        .library(name: "LeCodesSDK-3d", targets: ["LeCodesSDK3D"]),
        .library(name: "LeCodesSDK-2d", targets: ["LeCodesSDK2D"]),
        .library(name: "LeCodesSDK-core", targets: ["LeCodesSDKCore"]),
    ],
    targets: [
        .binaryTarget(
            name: "LeCodesSDKFull",
            url: "https://github.com/letary/lecodes-ios-sdk/releases/download/1.6.0/LeCodesSDK-full.xcframework.zip",
            checksum: "ada68c6c4da971144226a30678f0a592e15aea98196ab5033525d9131b62fe41"
        ),
        .binaryTarget(
            name: "LeCodesSDK3D",
            url: "https://github.com/letary/lecodes-ios-sdk/releases/download/1.6.0/LeCodesSDK-3d.xcframework.zip",
            checksum: "c4c447daae4789b2eb9fc83d3a59f468adf5fe23d162922957dea6b817a4186c"
        ),
        .binaryTarget(
            name: "LeCodesSDK2D",
            url: "https://github.com/letary/lecodes-ios-sdk/releases/download/1.6.0/LeCodesSDK-2d.xcframework.zip",
            checksum: "83475efe3947a281916ae18072d7617e464396d2b2c82a22d548504f70407a62"
        ),
        .binaryTarget(
            name: "LeCodesSDKCore",
            url: "https://github.com/letary/lecodes-ios-sdk/releases/download/1.6.0/LeCodesSDK-core.xcframework.zip",
            checksum: "09fc384b0063ca2fa97d68eee86bc64dd112795da5107e0515b6c121e2d5151d"
        ),
    ]
)
