// swift-tools-version:5.9
//
// LeCodesSDK 1.0.1 — binary distribution (no source).
// Generated by release.sh — do not edit by hand.
//
// Two variants, both vending the LeCodesSDK module (import is identical):
//   - LeCodesSDK-full: CreatorGL + filament (3D/AR)
//   - LeCodesSDK-core: UI only, ~15 MB smaller
//
// Full-variant consumers must also add LeCodesSDKResources.bundle (a release
// asset) to their app target's "Copy Bundle Resources".

import PackageDescription

let package = Package(
    name: "LeCodesSDK",
    platforms: [.iOS(.v14)],
    products: [
        .library(name: "LeCodesSDK-full", targets: ["LeCodesSDKFull"]),
        .library(name: "LeCodesSDK-core", targets: ["LeCodesSDKCore"]),
    ],
    targets: [
        .binaryTarget(
            name: "LeCodesSDKFull",
            url: "https://github.com/letary/lecodes-ios-sdk/releases/download/1.0.1/LeCodesSDK-full.xcframework.zip",
            checksum: "7eb70338c247b6c29fa18cb90f19c9711484ad4b081a7a8606094c07020ff2e8"
        ),
        .binaryTarget(
            name: "LeCodesSDKCore",
            url: "https://github.com/letary/lecodes-ios-sdk/releases/download/1.0.1/LeCodesSDK-core.xcframework.zip",
            checksum: "8e5bc825f61139ed4febc7731cf3251098fe270574a36a0165954236d9a0c719"
        ),
    ]
)
