// GENERATED by spec/generate.ts from spec/*.h — do not edit.

public let specVersion: Int32 = 1

public enum LineJoin: Int32 {
    case miter = 0
    case round = 1
    case bevel = 2
}

public enum LineCap: Int32 {
    case butt = 0
    case round = 1
    case square = 2
}

public enum TextAlign: Int32 {
    case left = 0
    case center = 1
    case right = 2
    case start = 3
    case end = 4
}

public enum TextBaseline: Int32 {
    case alphabetic = 0
    case top = 1
    case middle = 2
    case bottom = 3
    case hanging = 4
    case ideographic = 5
}

public enum FillRule: Int32 {
    case nonzero = 0
    case evenodd = 1
}

public enum Spread: Int32 {
    case pad = 0
    case reflect = 1
    case `repeat` = 2
}

public enum Gradient: Int32 {
    case linear = 0
    case radial = 1
}

public enum Paint: Int32 {
    case color = 0
    case linear = 1
    case radial = 2
}

public enum PathVerb: Int32 {
    case move = 0
    case line = 1
    case quad = 2
    case cubic = 3
    case close = 4
}

public enum ImageFormat: Int32 {
    case png = 0
    case jpeg = 1
}

/// The opcode stream: op id → the word after it.
public enum Op: Int32 {
    case save = 0
    case restore = 1
    case translate = 2
    case scale = 3
    case rotate = 4
    case transform = 5
    case setTransform = 6
    case resetTransform = 7
    case globalAlpha = 8
    case fillStyle = 9
    case strokeStyle = 10
    case fillGradient = 11
    case strokeGradient = 12
    case lineWidth = 13
    case lineJoin = 14
    case lineCap = 15
    case miterLimit = 16
    case lineDash = 17
    case lineDashOffset = 18
    case font = 19
    case textAlign = 20
    case textBaseline = 21
    case letterSpacing = 22
    case pathBegin = 23
    case pathClose = 24
    case moveTo = 25
    case lineTo = 26
    case quadraticTo = 27
    case bezierTo = 28
    case arc = 29
    case arcTo = 30
    case ellipse = 31
    case rect = 32
    case roundRect = 33
    case fill = 34
    case stroke = 35
    case clip = 36
    case fillRect = 37
    case strokeRect = 38
    case clearRect = 39
    case fillText = 40
    case strokeText = 41
    case drawImage = 42
}

/// The draw list commands. A painter switches over this enum exhaustively.
public enum DrawCmd: Int32 {
    case setTransform = 0
    case save = 1
    case restore = 2
    case clip = 3
    case fillPath = 4
    case strokePath = 5
    case fillText = 6
    case strokeText = 7
    case drawImage = 8
    case clearRect = 9
}
